name: Build Release APK

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./RemoteLG
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - uses: gradle/wrapper-validation-action@v1.0.4

      - name: Spotless check
        run: ./gradlew spotlessCheck

      - name: Build release APK
        run: ./gradlew assembleRelease --warning-mode all --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: RemoteLG/app/build/outputs/apk/release/*.apk
